//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirTemplateExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirTemplateExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        internal static string ContextMenu_CreateProject {
            get {
                return ResourceManager.GetString("ContextMenu_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize a new project from directory..
        /// </summary>
        internal static string ContextMenu_CreateProjectTooltip {
            get {
                return ResourceManager.GetString("ContextMenu_CreateProjectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize this directory from template &quot;{0}&quot;..
        /// </summary>
        internal static string ContextMenu_ItemTooltip {
            get {
                return ResourceManager.GetString("ContextMenu_ItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open templates directory.
        /// </summary>
        internal static string ContextMenu_OpenTemplateDir {
            get {
                return ResourceManager.GetString("ContextMenu_OpenTemplateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing a new project from {0} template....
        /// </summary>
        internal static string FormProgress_StatusLabel {
            get {
                return ResourceManager.GetString("FormProgress_StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project wizard.
        /// </summary>
        internal static string FormProgress_Title {
            get {
                return ResourceManager.GetString("FormProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &quot;{0}&quot; is not empty and contents may get overwritten.
        ///
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string InitializeProjectAction_NotEmptyDirWarning {
            get {
                return ResourceManager.GetString("InitializeProjectAction_NotEmptyDirWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not empty.
        /// </summary>
        internal static string InitializeProjectAction_NotEmptyDirWarningTitle {
            get {
                return ResourceManager.GetString("InitializeProjectAction_NotEmptyDirWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project initialization has been canceled..
        /// </summary>
        internal static string InitializeProjectAction_Worker_Canceled {
            get {
                return ResourceManager.GetString("InitializeProjectAction_Worker_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project initialization.
        /// </summary>
        internal static string InitializeProjectAction_Worker_CanceledTitle {
            get {
                return ResourceManager.GetString("InitializeProjectAction_Worker_CanceledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while initializing project.
        /// </summary>
        internal static string InitializeProjectAction_Worker_ErrorOccurred {
            get {
                return ResourceManager.GetString("InitializeProjectAction_Worker_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing project.
        /// </summary>
        internal static string InitializeProjectAction_Worker_ErrorOccurredTitle {
            get {
                return ResourceManager.GetString("InitializeProjectAction_Worker_ErrorOccurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InitProject {
            get {
                object obj = ResourceManager.GetObject("InitProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to system event logs: {0}
        ///
        ///Original error: {1}.
        /// </summary>
        internal static string Logger_Exception {
            get {
                return ResourceManager.GetString("Logger_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string Logger_WriteLog_ErrorTitle {
            get {
                return ResourceManager.GetString("Logger_WriteLog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open template directory. Please make sure that the following directory exists &quot;{0}&quot;..
        /// </summary>
        internal static string TemplateDir_OpenError {
            get {
                return ResourceManager.GetString("TemplateDir_OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening template directory.
        /// </summary>
        internal static string TemplateDir_OpenErrorBoxTitle {
            get {
                return ResourceManager.GetString("TemplateDir_OpenErrorBoxTitle", resourceCulture);
            }
        }
    }
}
